name: 更新 resource_list.json & Wiki

on:
  push:
    branches:
      - "main"
    paths:
      - "meme_generator/memes/**"
      - "meme_generator/memes_jj/**"
      - "meme_generator/memes_emoji/**"
      - "meme_generator/memes_other/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_resource_list:
    runs-on: ubuntu-latest
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 设置 uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: 更新 resource_list.json 文件
        run: un run tools/update_resource_list.py

      - name: 提交并推送更改
        uses: actions-js/push@master
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          message: "更新 resource_list.json"
          branch: "main"

  update_wiki:

    runs-on: ubuntu-latest
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 检出 Wiki 仓库
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki

      - name: 设置 uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: 安装依赖
        run: uv sync

      - name: 安装字体
        run: |
          sudo apt install fonts-noto-color-emoji libgl1 libglx-mesa0 libgl1-mesa-dri libegl1 libegl-mesa0
          sudo mkdir /usr/share/fonts/myfonts
          sudo cp resources/fonts/* /usr/share/fonts/myfonts/
          fc-cache -fv

      - name: 更新 memes.md 文件
        run: uv run wiki/update_meme_list.py

      - name: 提交并推送 Wiki 更新
        uses: actions-js/push@master
        with:
          directory: "wiki"
          repository: ${{ github.repository }}.wiki
          github_token: ${{ steps.app-token.outputs.token }}
          message: "更新 Meme 列表"
          branch: "master"
